processes:
  # 8080
  VALIDATOR-1:
    command: cd node/v1;  RUST_LOG=warn ../../bin/lumio-node --config configs/validator.yaml
  
  # 8081
  VALIDATOR-2:
    command: cd node/v2; RUST_LOG=warn ../../bin/lumio-node --config configs/validator.yaml

  # 8082
  VALIDATOR-3:
    command: cd node/v3; ../../bin/lumio-node --config configs/validator.yaml

  # 8083
  VALIDATOR-4:
    command: cd node/v4; ../../bin/lumio-node --config configs/validator.yaml

  # 8084
  VALIDATOR-5:
    command: cd node/v5; ../../bin/lumio-node --config configs/validator.yaml

  # 8085
  VALIDATOR-6:
    command: cd node/v6; ../../bin/lumio-node --config configs/validator.yaml

  # 50051-50052
  INDEXER-GRPC-MANAGER:
    command: 
      rm -rf ./tmp-indexer-data || true;
      mkdir ./tmp-indexer-data || true;
      RUST_LOG=info ./bin/lumio-indexer-grpc-manager --config-path ./grpc_manager.yaml
    
  GRPC-DATA-SERVICE:
    command: RUST_LOG=info ./bin/lumio-indexer-grpc-data-service-v2 --config-path ./grpc_data_service.yaml

