processes:
  VALIDATOR-1:
    command: cd node/v1; ../../bin/aptos-node --config configs/validator.yaml
  VALIDATOR-2:
    command: cd node/v2; ../../bin/aptos-node --config configs/validator.yaml

  VALIDATOR-3:
    command: cd node/v3; ../../bin/aptos-node --config configs/validator.yaml

  VALIDATOR-4:
    command: cd node/v4; ../../bin/aptos-node --config configs/validator.yaml

  VALIDATOR-5:
    command: cd node/v5; ../../bin/aptos-node --config configs/validator.yaml

  FULLNODE-6:
    command: cd node/v6; ../../bin/aptos-node --config configs/fullnode.yaml
