[package]
name = "test_update3"
version = "1.0.0"
authors = []

[addresses]
root = "0x1"

[dev-addresses]

[dependencies.LumioFramework]
git = "https://github.com/pontem-network/lumio-framework.git"
rev = "mainnet"
subdir = "lumio-framework"

[dev-dependencies]
